version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.21
    - 26.0.22
  - dependency-name: ts-jest
    versions:
    - 26.5.1
    - 26.5.2
    - 26.5.4
  - dependency-name: semantic-release
    versions:
    - 17.3.8
    - 17.3.9
    - 17.4.0
    - 17.4.1
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: commander
    versions:
    - 7.0.0
